### PR TITLE
a safer addition to address.hpp

### PR DESCRIPTION
**Pull request by akrzemi1**
This is a it safer alternative to https://github.com/solodon4/Mach7/pull/46.
It only works for `T*`, `std::unique_ptr<T>` and `std::shared_ptr<T>`. And it can be extended by users by means of specializing the new trait.

### CODE REVIEW

**Comment by solodon4** [comment]
I thought std::is_pointer would already be specialized for std::unique_ptr, std::shared_ptr, deprecated std::auto_ptr, isn't it? If it is not, i'd rather stick more overloads than overgeneralize by providing a customization point few would use. For now at least. This would cover most of the uses and wouldn't clutter readability.

**Comment by akrzemi1** [comment]
`std::is_pointer` is meant to only detect raw pointers. There is also `std::pointer_traits` specialized for `std::unique_ptr`, `std::shared_ptr`, `std::weak_ptr`, but there it cannot be used to test if a given type is a pointer or not.

Your minimal solution would solve my problem, so, I'll use it if I cannot convince you otherwise.

Note that if I only add specializations for `std` pointers, it will not handle a quite common case of `boost::shared_ptr`. I cannot add a specialization for `boost::shared_ptr` as it would tie Mach7 with Boost headers.

The library need not expose the customization point to the users, you can keep it an internal detail.

If it does not convince you, I'll submit a path with the minimal solution.

**Comment by solodon4** [comment]
My problem is not so much the customization point, but the quantity of them for every little thing that is already happening. The problem with having so many different customization points is that they are not easily discoverable - there are too many to remember, so no one would. This is why I was hoping if there is a standard one, we'd jump on it, but if there is no, I'm not convinced.

But that was my yesterday's thought. I was thinking more about it today during the event we had and I think I have the right solution in the spirit of Mach7 and XTL libraries. std::unique_ptr<T>, std::shared_ptr<T>, std::weak_ptr<T>, std::auto_ptr<T> and all their boost equivalents are a subtype of type T* (in the sense of customizable subtyping relation of XTL): their value can be used everywhere, where T* is accepted, but not the other way around. Because of this, we should use XTL's is_subtype and subtype_cast as a customization point and make address combinator take as a subject any type U, that is a subtype of T*. This will also jive well further when someone wants to try using variant<shared_ptr<T>, ...> where variant<T*, ...> is expected etc. 

What do you think? Would you like to try to pen it or shall I do it as an example for similar customizations we might need in the future? You can read more about XTL's subtyping relation here: https://parasol.tamu.edu/xtl/ There are links to papers and slides at the bottom. If you choose to read the paper, I recommend the extended version - it has more examples and improved discussion of issues. Let me know if any of the links doesn't work or something is not clear. Remember also that here in Mach7 we extended XTL with the analog of downcast (the original paper only has the safe upcast).

**Comment by akrzemi1** [comment]
Wow, a new material. I will be happy to read it. Seriously: i have yet to discover how this sub-type casting gets along with passing and catching by reference.

I would really prefer that you do it, as it is clear to me that I do not fully understand the power of XTL concept.

I do not fully follow how you see `unique_ptr<T>` as being an  xtl-subtype of `T*`. I would agree that a subset of the interface of `unique_ptr<T>` is an xtl-subtype of the subset of the interface of `T*`. Perhaps this is sufficient for the purpose of matching. I would agree that `unique_ptr<T> const` is an xtl-subtype of `T* const`.

But I might be simply misunderstanding the concept of xtl-subtyping.

**Comment by akrzemi1** [comment]
One thought. I do not fully understand the formal properties of sub-type to super-type relation. But from the examples with base classes and variant, I can see one property. You can convert a sub-type to a super-type. And the super-type contains sufficient information for you to be able to inspect what sub-type it has and convert back to the sub-type.

This property is not preserved in `unique_ptr<T>` to `T*` relation: once you convert a smart pointer to `T*` you do not know what special kind of smart pointer it used to be.

**Comment by akrzemi1** [comment]
Addressing the concern of the quantity of the customization points. Users need not know about them. I would expect a typical usage scenario to be like this.

I download the library and start to use it, also with pointers. It works fine with `T*` and `std::unique_ptr` and `std::shared_ptr`, so I do not need to bother about any details - probably to the end of my life.
On the other hand, if I one day try to use it with `boost::shared_ptr`, I find that it does not work. I start to dig. I discover that there is a customization point, I use it. And I can even forget about it again.

----

In a way a customization point like this is a temporary solution until we have concepts, or VS starts supporting SFINAE based on expressions.

**Pull request closed without merging**
