### PR TITLE
add installation support for cmake

### PR DESCRIPTION
**Pull request by FirstLoveLife**
https://github.com/solodon4/Mach7/issues/22

### CODE REVIEW

**Comment by solodon4** [comment]
Hi!

I tried to fix travis.ci due to updates in their images that started breaking the builds here and didn't realize my CR LF settings for this projects were off, so now the entire README.md got changed, making a conflict in this PR. Can you please merge with my changes and push into this PR again with conflicts resolved? I'll have a look at PR once that is done.

Thank you!

P.S. gcc on OSX still fails via Travis, but for some infrastructure reason. I'll have to figure that out later.

**Comment by solodon4** [comment]
You are trying to merge unresolved conflicts in multiple files

**Comment by FirstLoveLife** [comment]
rebase(my previoous commits mess up) have conflicit errors and I cannot fix them, so I restore feature branch from your master now.

**Comment by FirstLoveLife** [comment]
@solodon4 please take a look at https://github.com/solodon4/Mach7/pull/82/commits

**Pull request closed without merging**
